run:
  timeout: 3m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - gosimple
    - revive
    - gofmt
    - goimports
    - errorlint
    - bodyclose

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
